# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.13"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.5.4"
